// src/routes/stock/+page.svelte
<script lang="ts">
  import StockNavbar from "$lib/components/layout/stock-navbar.svelte";
  import FiltersBar from "$lib/components/stock/filters-bar.svelte";
  import FiltersTrigger from "$lib/components/stock/filters-trigger.svelte";
  import MobileFiltersSheet from "$lib/components/stock/mobile-filters-sheet.svelte";
  import ProductGrid from "$lib/components/stock/product-grid.svelte";
  import ProductDetailPanel from "$lib/components/stock/product-detail-panel.svelte";
  import MobileProductSheet from "$lib/components/stock/mobile-product-sheet.svelte";
  import { settingsStore } from "$lib/state/settings-store";
  import {
    getProductsPaginated,
    getProductsFilters,
    getFamilies,
    getProductById,
  } from "$lib/utils/stock-api";
  import { createAsyncStore } from "$lib/state/async-store.svelte";
  import { getStringParam, getNumberParam, writeSearchParams } from "$lib/utils/url-sync.svelte";
  import { createDebounced } from "$lib/utils/debounce.svelte";

  let panelPosition = $derived($settingsStore.panelPosition);
  let selectedProductId = $state<number | null>(null);
  let cachedProduct = $state<any>(null);

  let isMobile = $state(false);
  let filtersSheetOpen = $state(false);

  $effect(() => {
    if (typeof window === "undefined") return;
    const mql = window.matchMedia("(max-width: 1023px)");
    const handler = (e) => {
      isMobile = e.matches;
      if (!e.matches) filtersSheetOpen = false;
    };
    handler(mql);
    mql.addEventListener("change", handler);
    return () => mql.removeEventListener("change", handler);
  });

  let page = $state(getNumberParam("page", 1));
  let size = $state(getNumberParam("size", 64));
  let searchQuery = $state(getStringParam("search", ""));

  const defaultFilters = () => ({
    familia: getStringParam("familia", ""),
    disponibilidade: getStringParam("disponibilidade", "Todas"),
    cor: getStringParam("cor", ""),
    tamanho: getStringParam("tamanho", ""),
  });

  let appliedFilters = $state(defaultFilters());
  let pendingFilters = $state(defaultFilters());

  const familiesStore = createAsyncStore(getFamilies);
  const productsFiltersStore = createAsyncStore(getProductsFilters);

  let serverProducts = $state<any[]>([]);
  let serverTotal = $state(0);
  let serverLoading = $state(false);

  function buildQueryParams(p, s) {
    return {
      page: p,
      limit: s,
      search: searchQuery || undefined,
      familia: appliedFilters.familia ? appliedFilters.familia.split(",") : undefined,
      disponibilidade:
        appliedFilters.disponibilidade !== "Todas" ? appliedFilters.disponibilidade : undefined,
      cor: appliedFilters.cor ? appliedFilters.cor.split(",") : undefined,
      tamanho: appliedFilters.tamanho ? appliedFilters.tamanho.split(",") : undefined,
    };
  }

  async function doFetch(p, s) {
    serverLoading = true;
    try {
      const result = await getProductsPaginated(buildQueryParams(p, s));
      serverProducts = result.products;
      serverTotal = result.total;
      page = p;
    } catch {
      serverProducts = [];
      serverTotal = 0;
    } finally {
      serverLoading = false;
    }
  }

  const debouncedSearch = createDebounced(() => searchQuery, 300);

  $effect(() => {
    debouncedSearch.current;
    appliedFilters.familia;
    appliedFilters.disponibilidade;
    appliedFilters.cor;
    appliedFilters.tamanho;
    doFetch(1, size);
  });

  $effect(() => {
    writeSearchParams({
      page: page > 1 ? page : undefined,
      size: size !== 64 ? size : undefined,
      search: searchQuery || undefined,
      familia: appliedFilters.familia || undefined,
      disponibilidade:
        appliedFilters.disponibilidade !== "Todas" ? appliedFilters.disponibilidade : undefined,
      cor: appliedFilters.cor || undefined,
      tamanho: appliedFilters.tamanho || undefined,
    });
  });

  $effect(() => {
    const id = selectedProductId;
    if (id == null) return;
    const fresh = serverProducts.find((p) => p.id === id);
    if (fresh) cachedProduct = fresh;
  });

  let selectedProduct = $derived(
    selectedProductId != null && cachedProduct?.id === selectedProductId ? cachedProduct : null
  );

  async function refreshSelectedProduct() {
    if (selectedProductId == null) return;
    try {
      cachedProduct = await getProductById(selectedProductId);
    } catch {
      // ignore
    }
    doFetch(page, size);
  }

  function closeProduct() {
    selectedProductId = null;
    cachedProduct = null;
  }

  let availableColors = $derived(
    (productsFiltersStore.data?.colors || []).map((c) => (typeof c === "string" ? c : c.name))
  );
  let availableSizes = $derived(
    (productsFiltersStore.data?.sizes || []).map((s) => (typeof s === "string" ? s : s.size))
  );

  function countActive(f) {
    return (
      (f.familia ? 1 : 0) +
      (f.disponibilidade !== "Todas" ? 1 : 0) +
      (f.cor ? 1 : 0) +
      (f.tamanho ? 1 : 0)
    );
  }

  let activeFilterCount = $derived(countActive(appliedFilters));
  let pendingFilterCount = $derived(countActive(pendingFilters));
  let hasPendingChanges = $derived(
    pendingFilters.familia !== appliedFilters.familia ||
      pendingFilters.disponibilidade !== appliedFilters.disponibilidade ||
      pendingFilters.cor !== appliedFilters.cor ||
      pendingFilters.tamanho !== appliedFilters.tamanho
  );

  function syncAppliedToPending() {
    pendingFilters.familia = appliedFilters.familia;
    pendingFilters.disponibilidade = appliedFilters.disponibilidade;
    pendingFilters.cor = appliedFilters.cor;
    pendingFilters.tamanho = appliedFilters.tamanho;
  }

  function syncPendingToApplied() {
    appliedFilters.familia = pendingFilters.familia;
    appliedFilters.disponibilidade = pendingFilters.disponibilidade;
    appliedFilters.cor = pendingFilters.cor;
    appliedFilters.tamanho = pendingFilters.tamanho;
  }

  function applyFilters() {
    syncPendingToApplied();
    filtersSheetOpen = false;
  }

  function clearPending() {
    pendingFilters.familia = "";
    pendingFilters.disponibilidade = "Todas";
    pendingFilters.cor = "";
    pendingFilters.tamanho = "";
  }

  function clearAll() {
    clearPending();
    applyFilters();
  }

  function openFilters() {
    syncAppliedToPending();
    filtersSheetOpen = true;
  }
</script>

<div
  class="flex h-dvh flex-col bg-[#F3F4F6] p-1.5 sm:p-2 gap-1.5 sm:gap-2 transition-colors duration-250 dark:bg-slate-950"
>
  <StockNavbar bind:searchQuery />

  <div class="flex flex-1 overflow-hidden min-h-0 gap-1.5 sm:gap-2 relative">
    {#if !isMobile && panelPosition === "left" && selectedProduct}
      <ProductDetailPanel
        product={selectedProduct}
        onClose={closeProduct}
        onProductChange={refreshSelectedProduct}
      />
    {/if}

    <div
      class="flex flex-1 flex-col bg-white rounded-2xl border-2 border-slate-200 shadow-sm overflow-hidden transition-colors duration-250 dark:bg-slate-900 dark:border-slate-700 min-w-0"
    >
      <div class="lg:hidden px-3 pt-3 pb-1 shrink-0">
        <FiltersTrigger activeCount={pendingFilterCount} onOpen={openFilters} />
      </div>

      <FiltersBar
        families={familiesStore.data || []}
        {availableColors}
        {availableSizes}
        bind:pendingFilters
        onApply={applyFilters}
        onClear={clearAll}
        {hasPendingChanges}
        activeCount={activeFilterCount}
      />
      <ProductGrid
        products={serverProducts}
        totalRows={serverTotal}
        isLoading={serverLoading}
        bind:page
        bind:size
        bind:selectedId={selectedProductId}
        onPageChange={doFetch}
      />
    </div>

    {#if !isMobile && panelPosition === "right" && selectedProduct}
      <ProductDetailPanel
        product={selectedProduct}
        onClose={closeProduct}
        onProductChange={refreshSelectedProduct}
      />
    {/if}

    {#if isMobile && selectedProduct}
      <MobileProductSheet onClose={closeProduct}>
        <ProductDetailPanel
          product={selectedProduct}
          onClose={closeProduct}
          onProductChange={refreshSelectedProduct}
        />
      </MobileProductSheet>
    {/if}
  </div>
</div>

<MobileFiltersSheet
  bind:open={filtersSheetOpen}
  bind:pendingFilters
  families={familiesStore.data || []}
  {availableColors}
  {availableSizes}
  onApply={applyFilters}
  onClear={clearPending}
/>

// src/features/stock/index.tsx
import { useState, useMemo, useEffect } from "react";
import { useQuery } from "@tanstack/react-query";
import { StockNavbar } from "./components/stock-navbar";
import { FiltersBar } from "./components/filters-bar";
import { ProductGrid } from "./components/product-grid";
import { ProductDetailPanel } from "./components/product-detail-panel";
import { useSettingsStore } from "@/stores/settings-store";
import { getProducts, getFamilies } from "@/lib/stock-api";
import { toast } from "sonner";

export function StockPage() {
  const panelPosition = useSettingsStore((s) => s.panelPosition);
  const [selectedProductId, setSelectedProductId] = useState<number | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [filters, setFilters] = useState<Record<string, string>>({});

  const { data: products = [], isLoading, error: productsError } = useQuery({
    queryKey: ["stock-products"],
    queryFn: getProducts,
    retry: false,
  });

  const { data: families = [], error: familiesError } = useQuery({
    queryKey: ["stock-families"],
    queryFn: getFamilies,
    retry: false,
  });

  useEffect(() => {
    if (productsError) {
      const err = productsError as any;
      const status = err.response?.status;
      const message = err.response?.data?.message || err.message;
      if (status === 403) {
        toast.error(`Acesso negado: Não tens permissão para ver produtos. (${message})`);
      } else if (status === 401) {
        toast.error("Não autorizado. Faz login novamente.");
      } else if (status >= 500) {
        toast.error(`Erro interno no servidor ao carregar produtos. (${message})`);
      } else {
        toast.error(`Erro ao carregar produtos: ${message}`);
      }
    }
  }, [productsError]);

  useEffect(() => {
    if (familiesError) {
      const err = familiesError as any;
      const status = err.response?.status;
      const message = err.response?.data?.message || err.message;
      if (status === 403) {
        toast.error(`Acesso negado: Não tens permissão para ver famílias de produtos. (${message})`);
      } else {
        toast.error(`Erro ao carregar famílias: ${message}`);
      }
    }
  }, [familiesError]);

  const selectedProduct = useMemo(
    () => products.find((p) => p.id === selectedProductId) ?? null,
    [products, selectedProductId],
  );

  const filteredProducts = useMemo(() => {
    let result = products;

    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      result = result.filter(
        (p) =>
          p.ref.toLowerCase().includes(q) ||
          p.name.toLowerCase().includes(q) ||
          p.description?.toLowerCase().includes(q),
      );
    }

    if (filters.familia && filters.familia !== "Todas") {
      result = result.filter((p) => p.family?.name === filters.familia);
    }

    if (filters.cor && filters.cor !== "Todas") {
      result = result.filter((p) => p.colors?.some((c) => c.name === filters.cor));
    }

    if (filters.tamanho && filters.tamanho !== "Todas") {
      result = result.filter((p) => p.sizes?.some((s) => s.size === filters.tamanho));
    }

    if (filters.disponibilidade && filters.disponibilidade !== "Todas") {
      if (filters.disponibilidade === "Com Stock") {
        result = result.filter((p) => p.quantity > 0);
      } else if (filters.disponibilidade === "Esgotado") {
        result = result.filter((p) => p.quantity === 0);
      }
    }

    return result;
  }, [products, searchQuery, filters]);

  const availableColors = useMemo(() => {
    const set = new Set<string>();
    products.forEach((p) => p.colors?.forEach((c) => set.add(c.name)));
    return Array.from(set);
  }, [products]);

  const availableSizes = useMemo(() => {
    const set = new Set<string>();
    products.forEach((p) => p.sizes?.forEach((s) => set.add(s.size)));
    return Array.from(set);
  }, [products]);

  return (
    <div className="flex h-screen flex-col bg-[#F3F4F6] p-2 gap-2 transition-colors duration-250 dark:bg-slate-950">
      <StockNavbar searchQuery={searchQuery} onSearchChange={setSearchQuery} />
      <div className="flex flex-1 overflow-hidden min-h-0 gap-2">
        {panelPosition === "left" && selectedProduct && (
          <ProductDetailPanel
            product={selectedProduct}
            onClose={() => setSelectedProductId(null)}
          />
        )}

        <div className="flex flex-1 flex-col bg-white rounded-2xl border-2 border-slate-200 shadow-sm overflow-hidden transition-colors duration-250 dark:bg-slate-900 dark:border-slate-700">
          <FiltersBar
            families={families}
            availableColors={availableColors}
            availableSizes={availableSizes}
            filters={filters}
            onFilterChange={setFilters}
          />
          <ProductGrid
            products={filteredProducts}
            isLoading={isLoading}
            selectedId={selectedProductId}
            onSelectProduct={setSelectedProductId}
          />
        </div>

        {panelPosition === "right" && selectedProduct && (
          <ProductDetailPanel
            product={selectedProduct}
            onClose={() => setSelectedProductId(null)}
          />
        )}
      </div>
    </div>
  );
}
