// src/routes/auth/sign-in.svelte
<script>
  import Card from "@/lib/components/ui/card.svelte";
  import AuthLayout from "./auth-layout.svelte";
  import UserAuthForm from "./components/user-auth-form.svelte";
</script>

<AuthLayout>
  <Card class="gap-4">
    <div class="flex flex-col gap-1.5 p-6 pb-0">
      <h2 class="text-lg font-semibold leading-none tracking-tight">Entrar</h2>
      <p class="text-sm text-muted-foreground">
        Digite o seu email e password abaixo para <br />
        acessar a sua conta
      </p>
    </div>
    <div class="p-6 pt-0">
      <UserAuthForm />
    </div>
  </Card>
</AuthLayout>

// src/features/auth/sign-in/index.tsx
import { useSearch } from "@tanstack/react-router";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { AuthLayout } from "../auth-layout";
import { UserAuthForm } from "./components/user-auth-form";

export function SignIn() {
  const { redirect } = useSearch({ from: "/(auth)/sign-in" });

  return (
    <AuthLayout>
      <Card className="gap-4">
        <CardHeader>
          <CardTitle className="text-lg tracking-tight">Entrar</CardTitle>
          <CardDescription>
            Digite o seu email e password abaixo para <br />
            acessar a sua conta
          </CardDescription>
        </CardHeader>
        <CardContent>
          <UserAuthForm redirectTo={redirect} />
        </CardContent>
      </Card>
    </AuthLayout>
  );
}
