// src/components/ui/form-select-field.tsx
import { SearchableSelect, type SelectOption } from "@/components/ui/searchable-select";
import { FormField } from "@/components/ui/form-field";

type FormSelectFieldProps = {
  label: string;
  id?: string;
  value: string;
  onValueChange: (value: string) => void;
  options: SelectOption[];
  placeholder?: string;
  disabled?: boolean;
};

export function FormSelectField({ label, id, value, onValueChange, options, placeholder, disabled }: FormSelectFieldProps) {
  return (
    <FormField label={label} htmlFor={id}>
      <SearchableSelect id={id} value={value} onValueChange={onValueChange} options={options} placeholder={placeholder} disabled={disabled} />
    </FormField>
  );
}

// src/lib/components/ui/form-select-field.svelte
<script lang="ts">
  import SearchableSelect from "./searchable-select.svelte";
  import FormField from "./form-field.svelte";

  let {
    label = "",
    id = undefined,
    value = $bindable(""),
    options = [],
    placeholder = undefined,
    disabled = false,
    class: className = "",
  } = $props();
</script>

<FormField {label} for={id}>
  <SearchableSelect {id} bind:value {options} {placeholder} {disabled} class={className} />
</FormField>
