// src/components/ui/searchable-select.tsx
import * as React from "react";
import { createPortal } from "react-dom";
import { CheckIcon, ChevronDownIcon, SearchIcon } from "lucide-react";
import { cn } from "@/lib/utils";

export type SelectOption = {
  value: string;
  label: string;
};

type SearchableSelectProps = {
  value: string;
  onValueChange: (value: string) => void;
  options: SelectOption[];
  placeholder?: string;
  searchPlaceholder?: string;
  emptyMessage?: string;
  className?: string;
  disabled?: boolean;
  allowCustom?: boolean;
};

export function SearchableSelect({
  value,
  onValueChange,
  options,
  placeholder = "Select...",
  searchPlaceholder = "Search...",
  emptyMessage = "No results found.",
  className,
  disabled,
  allowCustom,
}: SearchableSelectProps) {
  const [open, setOpen] = React.useState(false);
  const [search, setSearch] = React.useState("");
  const [highlightedIndex, setHighlightedIndex] = React.useState(-1);
  const inputRef = React.useRef<HTMLInputElement>(null);
  const triggerRef = React.useRef<HTMLButtonElement>(null);
  const listRef = React.useRef<HTMLDivElement>(null);

  const filteredOptions = React.useMemo(() => {
    let result = search
      ? options.filter((o) =>
          o.label.toLowerCase().includes(search.toLowerCase()),
        )
      : options;

    if (allowCustom && search && !options.some((o) => o.label.toLowerCase() === search.toLowerCase())) {
      result = [{ value: search, label: search }, ...result];
    }

    return result;
  }, [options, search, allowCustom]);


  React.useEffect(() => {
    if (open) {
      inputRef.current?.focus();
    }
  }, [open]);

  React.useEffect(() => {
    if (!open) {
      setSearch("");
      setHighlightedIndex(-1);
    }
  }, [open]);

  React.useEffect(() => {
    setHighlightedIndex(-1);
  }, [search]);

  React.useEffect(() => {
    if (!open) return;
    const handleClickOutside = (e: MouseEvent) => {
      const target = e.target as Node;
      if (
        triggerRef.current?.contains(target) ||
        listRef.current?.contains(target)
      ) {
        return;
      }
      setOpen(false);
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [open]);

  React.useEffect(() => {
    if (!open) return;
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    document.addEventListener("keydown", handleEscape);
    return () => document.removeEventListener("keydown", handleEscape);
  }, [open]);

  const selectedOption = options.find((o) => o.value === value) || (value ? { value, label: value } : undefined);

  const selectOption = (optionValue: string) => {
    onValueChange(optionValue === value ? "" : optionValue);
    setOpen(false);
    triggerRef.current?.focus();
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    switch (e.key) {
      case "ArrowDown":
        e.preventDefault();
        setHighlightedIndex((prev) =>
          prev < filteredOptions.length - 1 ? prev + 1 : 0,
        );
        break;
      case "ArrowUp":
        e.preventDefault();
        setHighlightedIndex((prev) =>
          prev > 0 ? prev - 1 : filteredOptions.length - 1,
        );
        break;
      case "Enter":
        e.preventDefault();
        if (
          highlightedIndex >= 0 &&
          highlightedIndex < filteredOptions.length
        ) {
          selectOption(filteredOptions[highlightedIndex].value);
        }
        break;
    }
  };

  const [triggerRect, setTriggerRect] = React.useState<DOMRect | null>(null);

  const handleTriggerClick = () => {
    if (disabled) return;
    const rect = triggerRef.current?.getBoundingClientRect();
    if (rect) setTriggerRect(rect);
    setOpen((prev) => !prev);
  };

  return (
    <div className="relative">
      <button
        ref={triggerRef}
        type="button"
        role="combobox"
        aria-expanded={open}
        aria-haspopup="listbox"
        disabled={disabled}
        onClick={handleTriggerClick}
        className={cn(
          "flex h-10 w-full items-center justify-between rounded-lg border border-slate-200 bg-white px-3 text-sm font-normal hover:bg-slate-50 dark:border-slate-850 dark:bg-slate-950 dark:hover:bg-slate-800/80",
          !selectedOption && "text-muted-foreground",
          className,
        )}
      >
        {selectedOption ? selectedOption.label : placeholder}
        <ChevronDownIcon
          className={cn(
            "ml-2 h-4 w-4 shrink-0 opacity-50 transition-transform",
            open && "rotate-180",
          )}
        />
      </button>

      {open &&
        triggerRect &&
        createPortal(
          <div
            ref={listRef}
            role="listbox"
            onKeyDown={handleKeyDown}
            style={{
              position: "fixed",
              top: `${triggerRect.bottom + 4}px`,
              left: `${triggerRect.left}px`,
              width: `${triggerRect.width}px`,
              zIndex: 9999,
            }}
            className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-md dark:border-slate-850 dark:bg-slate-950"
          >
            <div className="flex items-center border-b border-slate-200 px-3 dark:border-slate-800">
              <SearchIcon className="mr-2 h-4 w-4 shrink-0 text-slate-400" />
              <input
                ref={inputRef}
                type="text"
                placeholder={searchPlaceholder}
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="flex h-10 w-full bg-transparent py-3 text-sm outline-none placeholder:text-slate-400"
              />
            </div>
            <div className="max-h-[300px] overflow-y-auto overflow-x-hidden p-1">
              {filteredOptions.length === 0 ? (
                <div className="py-6 text-center text-sm text-slate-500">
                  {emptyMessage}
                </div>
              ) : (
                filteredOptions.map((option, index) => (
                  <div
                    key={option.value}
                    role="option"
                    aria-selected={value === option.value}
                    onClick={() => selectOption(option.value)}
                    onMouseEnter={() => setHighlightedIndex(index)}
                    className={cn(
                      "relative flex cursor-default items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-none select-none",
                      highlightedIndex === index &&
                        "bg-slate-100 dark:bg-slate-800",
                      value === option.value
                        ? "text-slate-900 dark:text-slate-100"
                        : "text-slate-700 dark:text-slate-300",
                    )}
                  >
                    {option.label}
                    <CheckIcon
                      className={cn(
                        "ml-auto h-4 w-4",
                        value === option.value
                          ? "opacity-100"
                          : "opacity-0",
                      )}
                    />
                  </div>
                ))
              )}
            </div>
          </div>,
          document.body,
        )}
    </div>
  );
}

// src/lib/components/ui/searchable-select.svelte
<script lang="ts">
  import { Check, ChevronsUpDown } from "lucide-svelte";
  import { cn } from "$lib/utils";
  import { tick } from "svelte";
  import { portal } from "$lib/utils/portal";

  let {
    id = undefined,
    value = $bindable(""),
    options = [],
    placeholder = "Selecionar",
    searchPlaceholder = "Pesquisar...",
    emptyMessage = "Sem resultados.",
    class: className = "",
    disabled = false,
  } = $props();

  let open = $state(false);
  let search = $state("");
  let triggerEl = $state<HTMLDivElement | null>(null);
  let listEl = $state<HTMLDivElement | null>(null);
  let listStyle = $state("");
  let openUpward = $state(false);

  let selected = $derived(options.find((o) => o.value === value));

  let filteredOptions = $derived(
    search ? options.filter((o) => o.label.toLowerCase().includes(search.toLowerCase())) : options
  );

  async function handleSelect(optValue) {
    value = optValue === value ? "" : optValue;
    open = false;
    search = "";
  }

  function updatePosition() {
    if (!triggerEl) return;
    const rect = triggerEl.getBoundingClientRect();
    const dropdownH = Math.min(320, window.innerHeight * 0.6);
    const viewportH = window.innerHeight;
    const margin = 8;
    const spaceBelow = viewportH - rect.bottom - margin;
    const spaceAbove = rect.top - margin;
    openUpward = spaceBelow < dropdownH && spaceAbove > spaceBelow;
    const top = openUpward
      ? Math.max(margin, rect.top - dropdownH - 4)
      : Math.min(viewportH - dropdownH - margin, rect.bottom + 4);
    const width = rect.width;
    let left = rect.left;
    const minLeft = margin;
    const maxLeft = window.innerWidth - width - margin;
    if (left < minLeft) left = minLeft;
    if (left > maxLeft) left = maxLeft;
    listStyle = `position: fixed; top: ${top}px; left: ${left}px; width: ${width}px;`;
  }

  async function openDropdown() {
    if (disabled) return;
    open = true;
    search = "";
    await tick();
    updatePosition();
  }

  function closeDropdown() {
    open = false;
    search = "";
  }

  function handleClickOutside(e) {
    if (!open) return;
    if (triggerEl && triggerEl.contains(e.target)) return;
    if (listEl && listEl.contains(e.target)) return;
    closeDropdown();
  }
</script>

<svelte:window onclick={handleClickOutside} onresize={updatePosition} onscroll={updatePosition} />

<div class="relative" bind:this={triggerEl}>
  <button
    type="button"
    {id}
    {disabled}
    role="combobox"
    aria-expanded={open}
    aria-controls={id ? `${id}-listbox` : undefined}
    class={cn(
      "flex w-full min-w-0 shrink items-center justify-between overflow-hidden font-normal h-9 rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50",
      !selected && "text-muted-foreground",
      className
    )}
    onclick={(e) => {
      e.stopPropagation();
      if (open) closeDropdown();
      else openDropdown();
    }}
  >
    <span class="truncate">{selected?.label ?? placeholder}</span>
    <ChevronsUpDown class="ml-1 size-4 shrink-0 opacity-50" />
  </button>
</div>

{#if open}
  <div
    use:portal
    bind:this={listEl}
    id={id ? `${id}-listbox` : undefined}
    role="listbox"
    style={listStyle}
    class="z-[200] rounded-md border bg-popover text-popover-foreground shadow-md overflow-hidden"
  >
    <div class="flex items-center border-b px-3">
      <input
        type="text"
        class="flex h-9 w-full rounded-md bg-transparent py-3 text-sm outline-none placeholder:text-muted-foreground"
        placeholder={searchPlaceholder}
        bind:value={search}
      />
    </div>
    <div class="max-h-[300px] overflow-y-auto p-1">
      {#if filteredOptions.length === 0}
        <div class="py-6 text-center text-sm">{emptyMessage}</div>
      {:else}
        {#each filteredOptions as opt (opt.value)}
          <button
            type="button"
            role="option"
            aria-selected={value === opt.value}
            class="relative flex w-full cursor-default items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-none select-none hover:bg-accent hover:text-accent-foreground"
            onclick={() => handleSelect(opt.value)}
          >
            <Check
              class={cn("size-4 shrink-0", value === opt.value ? "opacity-100" : "opacity-0")}
            />
            {opt.label}
          </button>
        {/each}
      {/if}
    </div>
  </div>
{/if}
