// src/features/auth/forgot-password/index.tsx
import { Link } from "@tanstack/react-router";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { AuthLayout } from "../auth-layout";
import { ForgotPasswordForm } from "./components/forgot-password-form";

export function ForgotPassword() {
  return (
    <AuthLayout>
      <Card className="gap-4">
        <CardHeader>
          <CardTitle className="text-lg tracking-tight">
            Esqueci minha password
          </CardTitle>
          <CardDescription>
            Digite o seu email e <br /> enviaremos um link para mudar a sua
            password.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ForgotPasswordForm />
        </CardContent>
        <CardFooter>
          <p className="text-muted-foreground mx-auto px-8 text-center text-sm text-balance">
            Lembrou-se da sua password?{" "}
            <Link
              to="/sign-in"
              className="hover:text-primary underline underline-offset-4"
            >
              Entrar
            </Link>
            .
          </p>
        </CardFooter>
      </Card>
    </AuthLayout>
  );
}

// src/routes/forgot-password/+page.svelte
<script lang="ts">
  import { navigateTo } from "$lib/utils/navigate";
  import Card from "$lib/components/ui/card.svelte";
  import AuthLayout from "$lib/components/auth/auth-layout.svelte";
  import ForgotPasswordForm from "$lib/components/auth/forgot-password-form.svelte";
</script>

<AuthLayout>
  <Card class="gap-4">
    <div class="flex flex-col gap-1.5 p-6 pb-0">
      <h2 class="text-lg font-semibold tracking-tight">Esqueci minha password</h2>
      <p class="text-sm text-muted-foreground">
        Digite o seu email e <br /> enviaremos um link para mudar a sua password.
      </p>
    </div>
    <div class="p-6 pt-0">
      <ForgotPasswordForm />
    </div>
    <div class="p-6 pt-0">
      <p class="text-muted-foreground mx-auto px-8 text-center text-sm text-balance">
        Lembrou-se da sua password?{" "}
        <a
          href="/sign-in"
          onclick={(e) => {
            e.preventDefault();
            navigateTo("/sign-in");
          }}
          class="hover:text-primary underline underline-offset-4"
        >
          Entrar
        </a>
        .
      </p>
    </div>
  </Card>
</AuthLayout>
