// src/features/auth/forgot-password/components/forgot-password-form.tsx
import { useTransition } from "react";
import { z } from "zod";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useNavigate } from "@tanstack/react-router";
import { ArrowRight, Loader2 } from "@/lib/icon-map";
import { toast } from "sonner";
import { sleep, cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";

const formSchema = z.object({
  email: z
    .string()
    .min(1, "Por favor, digite seu email")
    .email("Email inválido"),
});

export function ForgotPasswordForm({
  className,
  ...props
}: React.HTMLAttributes<HTMLFormElement>) {
  const navigate = useNavigate();
  const [isPending, startTransition] = useTransition();

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: { email: "" },
  });

  function onSubmit(data: z.infer<typeof formSchema>) {
    startTransition(async () => {
      toast.promise(sleep(2000), {
        loading: "A enviar email...",
        success: () => {
          form.reset();
          navigate({ to: "/otp" });
          return `Email enviado para ${data.email}`;
        },
        error: "Error",
      });
    });
  }

  return (
    <Form {...form}>
      <form
        onSubmit={form.handleSubmit(onSubmit)}
        className={cn("grid gap-2", className)}
        {...props}
      >
        <FormField
          control={form.control}
          name="email"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Email</FormLabel>
              <FormControl>
                <Input placeholder="nome@exemplo.com" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <Button className="mt-2" disabled={isPending}>
          Continuar
          {isPending ? <Loader2 className="animate-spin" /> : <ArrowRight />}
        </Button>
      </form>
    </Form>
  );
}

// src/lib/components/auth/forgot-password-form.svelte
<script lang="ts">
  import { z } from "zod";
  import { navigateTo } from "$lib/utils/navigate";
  import { ArrowRight, Loader2 } from "lucide-svelte";
  import { toast } from "svelte-sonner";
  import { sleep, cn } from "$lib/utils";
  import Button from "$lib/components/ui/button.svelte";
  import Input from "$lib/components/ui/input.svelte";
  import Label from "$lib/components/ui/label.svelte";

  const formSchema = z.object({
    email: z.string().min(1, "Por favor, digite seu email").email("Email inválido"),
  });

  let isPending = $state(false);
  let email = $state("");
  let errors = $state({ email: "" });

  async function onSubmit(e) {
    e.preventDefault();
    errors = { email: "" };

    const result = formSchema.safeParse({ email });
    if (!result.success) {
      const fieldErrors = result.error.flatten().fieldErrors;
      errors = { email: fieldErrors.email?.[0] || "" };
      return;
    }

    isPending = true;
    toast.promise(sleep(2000), {
      loading: "A enviar email...",
      success: () => {
        navigateTo("/otp");
        return `Email enviado para ${email}`;
      },
      error: "Error",
    });
    isPending = false;
  }
</script>

<form onsubmit={onSubmit} class={cn("grid gap-2")}>
  <div class="flex flex-col gap-1.5">
    <Label for="email">Email</Label>
    <Input id="email" type="email" placeholder="nome@exemplo.com" bind:value={email} />
    {#if errors.email}
      <span class="text-[0.8rem] font-medium text-destructive">{errors.email}</span>
    {/if}
  </div>
  <Button type="submit" class="mt-2" disabled={isPending}>
    Continuar
    {#if isPending}
      <Loader2 class="animate-spin" />
    {:else}
      <ArrowRight />
    {/if}
  </Button>
</form>
