// src/lib/components/auth/auth-layout.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  let { children }: { children: Snippet } = $props();
</script>

<div
  class="min-h-dvh flex flex-col items-center justify-center bg-[#F3F4F6] dark:bg-slate-950 p-4 gap-4"
>
  <div class="flex items-center gap-2">
    <span class="text-2xl font-extrabold tracking-tight text-slate-800 dark:text-white"
      >Brindicis Stock</span
    >
  </div>
  {@render children?.()}
</div>

// src/features/auth/auth-layout.tsx
import { Logo } from "@/assets/logo";

type AuthLayoutProps = {
  children: React.ReactNode;
};

export function AuthLayout({ children }: AuthLayoutProps) {
  return (
    <div className="container grid h-svh max-w-none items-center justify-center">
      <div className="mx-auto flex w-full flex-col justify-center gap-y-2 py-8 sm:w-[480px] sm:p-8">
        <div className="mb-6 flex flex-col items-center gap-2">
          <Logo className="h-20 w-auto" />
          <h1 className="text-2xl font-semibold tracking-tight">
            Brindicis Stock
          </h1>
        </div>
        {children}
      </div>
    </div>
  );
}
