// src/routes/otp/+page.svelte
<script lang="ts">
  import { navigateTo } from "$lib/utils/navigate";
  import Card from "$lib/components/ui/card.svelte";
  import AuthLayout from "$lib/components/auth/auth-layout.svelte";
  import OtpForm from "$lib/components/auth/otp-form.svelte";
</script>

<AuthLayout>
  <Card class="gap-4">
    <div class="flex flex-col gap-1.5 p-6 pb-0">
      <h2 class="text-base font-semibold tracking-tight">Digite o código de autenticação</h2>
      <p class="text-sm text-muted-foreground">
        Por favor, digite o código de autenticação. <br /> Enviamos o código de autenticação para o seu
        email.
      </p>
    </div>
    <div class="p-6 pt-0">
      <OtpForm />
    </div>
    <div class="p-6 pt-0">
      <p class="text-muted-foreground px-8 text-center text-sm">
        Não recebeu o código?{" "}
        <a
          href="/sign-in"
          onclick={(e) => {
            e.preventDefault();
            navigateTo("/sign-in");
          }}
          class="hover:text-primary underline underline-offset-4"
        >
          Reenviar um novo código.
        </a>
        .
      </p>
    </div>
  </Card>
</AuthLayout>

// src/features/auth/otp/index.tsx
import { Link } from "@tanstack/react-router";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { AuthLayout } from "../auth-layout";
import { OtpForm } from "./components/otp-form";

export function Otp() {
  return (
    <AuthLayout>
      <Card className="gap-4">
        <CardHeader>
          <CardTitle className="text-base tracking-tight">
            Digite o código de autenticação
          </CardTitle>
          <CardDescription>
            Por favor, digite o código de autenticação. <br /> Enviamos o código
            de autenticação para o seu email.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <OtpForm />
        </CardContent>
        <CardFooter>
          <p className="text-muted-foreground px-8 text-center text-sm">
            Não recebeu o código?{" "}
            <Link
              to="/sign-in"
              className="hover:text-primary underline underline-offset-4"
            >
              Reenviar um novo código.
            </Link>
            .
          </p>
        </CardFooter>
      </Card>
    </AuthLayout>
  );
}
