// src/lib/components/ui/data-table.svelte
<script>
  import { Loader2, ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from "@/lib/utils/icon-map";
  import Button from "./button.svelte";

  let {
    columns = [],
    data = [],
    isLoading = false,
    loadingMessage = "A carregar...",
    emptyMessage = "Sem dados disponíveis.",
    rowKey = (row) => row.id,
    onRowClick = undefined,
    pageSize = 25,
    showPagination = true,
    pageSizeOptions = [25, 50, 100, 250],
    cell = undefined,
  } = $props();

  let page = $state(1);
  let size = $state(25);

  $effect(() => {
    size = pageSize;
  });

  let totalPages = $derived(Math.max(1, Math.ceil(data.length / size)));
  let safePage = $derived(Math.min(page, totalPages));
  let start = $derived((safePage - 1) * size);
  let pageData = $derived(data.slice(start, start + size));
  let showBar = $derived(showPagination && !isLoading && data.length > 0);
</script>

<div class="bg-white rounded-2xl border border-slate-200/60 transition-colors duration-250 dark:bg-slate-900 dark:border-slate-800/80 overflow-hidden flex flex-col flex-1 min-h-0">
  <div class="flex-1 overflow-y-auto overflow-x-auto min-h-0">
    <table class="w-full text-left border-collapse">
      <thead class="sticky top-0 z-10 bg-white dark:bg-slate-900">
        <tr class="bg-slate-50/50 border-b border-slate-100 dark:bg-slate-900/50 dark:border-slate-800/80">
          {#each columns as col (col.key)}
            <th class="px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500 {col.headerClassName ?? ''}">
              {col.header}
            </th>
          {/each}
        </tr>
      </thead>
      <tbody>
        {#if isLoading}
          <tr>
            <td colspan={columns.length} class="px-6 py-16 text-center">
              <div class="flex flex-col items-center justify-center gap-2">
                <Loader2 class="size-6 animate-spin text-amber-400" />
                <span class="text-sm text-slate-400 dark:text-slate-500">{loadingMessage}</span>
              </div>
            </td>
          </tr>
        {:else if data.length === 0}
          <tr>
            <td colspan={columns.length} class="px-6 py-24 text-center">
              <span class="text-sm font-medium text-slate-400 dark:text-slate-500">{emptyMessage}</span>
            </td>
          </tr>
        {:else}
          {#each pageData as row, i (rowKey(row))}
            <tr
              class="border-b border-slate-100 last:border-0 transition-colors dark:border-slate-800/60 {onRowClick ? 'cursor-pointer' : ''} hover:bg-slate-50/30 dark:hover:bg-slate-800/10 {i % 2 === 0 ? 'bg-white dark:bg-slate-900' : 'bg-slate-50/20 dark:bg-slate-800/5'}"
              onclick={() => onRowClick?.(row)}
            >
              {#each columns as col (col.key)}
                <td class="px-5 py-3 text-sm {col.className ?? 'text-slate-800 dark:text-slate-200'}">
                  {#if cell}
                    {@render cell(row, col)}
                  {:else if col.render}
                    {@html col.render(row)}
                  {/if}
                </td>
              {/each}
            </tr>
          {/each}
        {/if}
      </tbody>
    </table>
  </div>

  {#if showBar}
    <div class="flex items-center justify-between px-5 py-3 border-t border-slate-100 dark:border-slate-800/60 bg-white dark:bg-slate-900 shrink-0">
      <div class="flex items-center gap-2">
        <select
          bind:value={size}
          onchange={() => { page = 1; }}
          class="h-7 rounded-md border border-slate-200 bg-white px-2 text-xs text-slate-600 focus:outline-none dark:border-slate-800 dark:bg-slate-950 dark:text-slate-400"
        >
          {#each pageSizeOptions as opt}
            <option value={opt}>{opt}</option>
          {/each}
        </select>
        <span class="text-xs text-slate-400 dark:text-slate-500">linhas por página · {data.length} registos</span>
      </div>
      <div class="flex items-center gap-1.5">
        <span class="text-xs text-slate-500 dark:text-slate-400 mr-2">
          Página {safePage} de {totalPages}
        </span>
        <Button variant="outline" size="icon" disabled={safePage <= 1} onclick={() => page = 1} class="size-7">
          <ChevronsLeft class="size-3.5" />
        </Button>
        <Button variant="outline" size="icon" disabled={safePage <= 1} onclick={() => page = Math.max(1, page - 1)} class="size-7">
          <ChevronLeft class="size-3.5" />
        </Button>
        <Button variant="outline" size="icon" class="size-7 bg-amber-400 text-[#1F2937] hover:bg-amber-500 border-none cursor-default text-xs font-bold">
          {safePage}
        </Button>
        <Button variant="outline" size="icon" disabled={safePage >= totalPages} onclick={() => page = Math.min(totalPages, page + 1)} class="size-7">
          <ChevronRight class="size-3.5" />
        </Button>
        <Button variant="outline" size="icon" disabled={safePage >= totalPages} onclick={() => page = totalPages} class="size-7">
          <ChevronsRight class="size-3.5" />
        </Button>
      </div>
    </div>
  {/if}
</div>

// src/components/ui/data-table.tsx
import { useState, useMemo } from "react";
import { Loader2, ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from "lucide-react";
import { Button } from "@/components/ui/button";

export type Column<T> = {
  key: string;
  header: string;
  cell: (row: T) => React.ReactNode;
  className?: string;
  headerClassName?: string;
};

type DataTableProps<T> = {
  columns: Column<T>[];
  data: T[];
  isLoading?: boolean;
  loadingMessage?: string;
  emptyMessage?: string;
  rowKey: (row: T) => string | number;
  onRowClick?: (row: T) => void;
  pageSize?: number;
  showPagination?: boolean;
  pageSizeOptions?: number[];
};

export function DataTable<T>({
  columns,
  data,
  isLoading,
  loadingMessage = "A carregar...",
  emptyMessage = "Sem dados disponíveis.",
  rowKey,
  onRowClick,
  pageSize = 25,
  showPagination = true,
  pageSizeOptions = [25, 50, 100, 250],
}: DataTableProps<T>) {
  const [page, setPage] = useState(1);
  const [size, setSize] = useState(pageSize);

  const totalPages = useMemo(() => Math.max(1, Math.ceil(data.length / size)), [data.length, size]);
  const safePage = Math.min(page, totalPages);
  const start = (safePage - 1) * size;
  const pageData = data.slice(start, start + size);

  const showBar = showPagination && !isLoading && data.length > 0;

  return (
    <div className="bg-white rounded-2xl border border-slate-200/60 transition-colors duration-250 dark:bg-slate-900 dark:border-slate-800/80 overflow-hidden flex flex-col flex-1 min-h-0">
      <div className="flex-1 overflow-y-auto overflow-x-auto min-h-0">
        <table className="w-full text-left border-collapse">
          <thead className="sticky top-0 z-10 bg-white dark:bg-slate-900">
            <tr className="bg-slate-50/50 border-b border-slate-100 dark:bg-slate-900/50 dark:border-slate-800/80">
              {columns.map((col) => (
                <th
                  key={col.key}
                  className={`px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500 ${col.headerClassName ?? ""}`}
                >
                  {col.header}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {isLoading ? (
              <tr>
                <td colSpan={columns.length} className="px-6 py-16 text-center">
                  <div className="flex flex-col items-center justify-center gap-2">
                    <Loader2 className="size-6 animate-spin text-amber-400" />
                    <span className="text-sm text-slate-400 dark:text-slate-500">{loadingMessage}</span>
                  </div>
                </td>
              </tr>
            ) : data.length === 0 ? (
              <tr>
                <td colSpan={columns.length} className="px-6 py-24 text-center">
                  <span className="text-sm font-medium text-slate-400 dark:text-slate-500">{emptyMessage}</span>
                </td>
              </tr>
            ) : (
              pageData.map((row, i) => (
                <tr
                  key={rowKey(row)}
                  onClick={() => onRowClick?.(row)}
                  className={`border-b border-slate-100 last:border-0 transition-colors dark:border-slate-800/60 ${onRowClick ? "cursor-pointer" : ""} hover:bg-slate-50/30 dark:hover:bg-slate-800/10 ${i % 2 === 0 ? "bg-white dark:bg-slate-900" : "bg-slate-50/20 dark:bg-slate-800/5"}`}
                >
                  {columns.map((col) => (
                    <td key={col.key} className={`px-5 py-3 text-sm ${col.className ?? "text-slate-800 dark:text-slate-200"}`}>
                      {col.cell(row)}
                    </td>
                  ))}
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {showBar && (
        <div className="flex items-center justify-between px-5 py-3 border-t border-slate-100 dark:border-slate-800/60 bg-white dark:bg-slate-900 shrink-0">
          <div className="flex items-center gap-2">
            <select
              value={size}
              onChange={(e) => { setSize(Number(e.target.value)); setPage(1); }}
              className="h-7 rounded-md border border-slate-200 bg-white px-2 text-xs text-slate-600 focus:outline-none dark:border-slate-800 dark:bg-slate-950 dark:text-slate-400"
            >
              {pageSizeOptions.map((opt) => (
                <option key={opt} value={opt}>{opt}</option>
              ))}
            </select>
            <span className="text-xs text-slate-400 dark:text-slate-500">linhas por página · {data.length} registos</span>
          </div>
          <div className="flex items-center gap-1.5">
            <span className="text-xs text-slate-500 dark:text-slate-400 mr-2">
              Página {safePage} de {totalPages}
            </span>
            <Button variant="outline" size="icon" disabled={safePage <= 1} onClick={() => setPage(1)} className="size-7">
              <ChevronsLeft className="size-3.5" />
            </Button>
            <Button variant="outline" size="icon" disabled={safePage <= 1} onClick={() => setPage((p) => Math.max(1, p - 1))} className="size-7">
              <ChevronLeft className="size-3.5" />
            </Button>
            <Button variant="outline" size="icon" className="size-7 bg-amber-400 text-[#1F2937] hover:bg-amber-500 border-none cursor-default text-xs font-bold">
              {safePage}
            </Button>
            <Button variant="outline" size="icon" disabled={safePage >= totalPages} onClick={() => setPage((p) => Math.min(totalPages, p + 1))} className="size-7">
              <ChevronRight className="size-3.5" />
            </Button>
            <Button variant="outline" size="icon" disabled={safePage >= totalPages} onClick={() => setPage(totalPages)} className="size-7">
              <ChevronsRight className="size-3.5" />
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
